path_to_train: "/mnt/storage/data/work/g2p/data/train.txt"
path_train_dataset: "/mnt/storage/data/work/g2p/train_dataset"
path_val_dataset: "/mnt/storage/data/work/g2p/val_dataset"
path_to_save_model: "./models/deep_blstm/model_deep_blstm"
path_to_config_model: "./models/deep_blstm/config_deep_blstm.yaml"
path_to_checkpoint: "./models/deep_blstm/ckpt/best.ckpt"
batch_size: 16
epochs: 30